CubeSummation.Web/Models/CalculoCubo.cs
using System;

namespace CubeSummation.Web.Models
{
    public static class CalculoCubo
    {
        static int T, N, M;
        static int[,,] Matriz3D;

        public static string CalcularDatos(string secuencia)
        {
            try
            {
                string resultado = string.Empty;

                int posSecuencia = 0;
                string[] listaSecuencia = secuencia.Split("\n");
                T = Convert.ToInt32(listaSecuencia[posSecuencia]);

                for (int i = 0; i < T; i++)
                {
                    posSecuencia += 1;
                    string[] NMLineParts = listaSecuencia[posSecuencia].Trim().Split(" ");
                    N = Convert.ToInt32(NMLineParts[0]);
                    M = Convert.ToInt32(NMLineParts[1]);
                    Matriz3D = new int[N + 1, N + 1, N + 1];

                    for (int j = 0; j < M; j++)
                    {
                        posSecuencia = posSecuencia + 1;
                        string Operacion = listaSecuencia[posSecuencia];

                        string[] OperacionLineParts = Operacion.Split(" ");
                        if (OperacionLineParts[0].Equals("UPDATE"))
                        {
                            Actualizar(Convert.ToInt32(OperacionLineParts[1]), Convert.ToInt32(OperacionLineParts[2]), Convert.ToInt32(OperacionLineParts[3]), Convert.ToInt32(OperacionLineParts[4]));
                        }
                        if (OperacionLineParts[0].Equals("QUERY"))
                        {
                            resultado = resultado +
                                Consulta(Convert.ToInt32(OperacionLineParts[1]), Convert.ToInt32(OperacionLineParts[2]), Convert.ToInt32(OperacionLineParts[3]), Convert.ToInt32(OperacionLineParts[4]), Convert.ToInt32(OperacionLineParts[5]), Convert.ToInt32(OperacionLineParts[6]))
                                + "\n";
                        }
                    }
                }
                return resultado;
            }
            catch
            {
                return "Varificar texto de entrada.";
            }            
        }

        private static void Actualizar(int x, int y, int z, int valor)
        {
            Matriz3D[x, y, z] = valor;
        }

        private static string Consulta(int x1, int y1, int z1, int x2, int y2, int z2)
        {
            int sum = 0;
            for (int x = 0; x <= N; x++)
            {
                for (int y = 0; y <= N; y++)
                {
                    for (int z = 0; z <= N; z++)
                    {
                        if ((x >= x1 && y >= y1 && z >= z1) &&
                            (x <= x2 && y <= y2 && z <= z2))
                        {
                            sum += Matriz3D[x, y, z];
                        }
                    }
                }
            }
            return sum.ToString();
        }



    }
}

CubeSummation.Web/Models/ErrorViewModel.cs
using System;

namespace CubeSummation.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CubeSummation.Web/Controllers/CubeSummationController.cs
using CubeSummation.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace CubeSummation.Web.Controllers
{
    public class CubeSummationController : Controller
    {
        public ActionResult Index()
        { 
            return View();
        }

        public JsonResult Proceso(string texto)
        { 
            return Json(CalculoCubo.CalcularDatos(texto));
        }

    }
}

CubeSummation.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CubeSummation.Web.Models;

namespace CubeSummation.Web.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CubeSummation.Web/Views/CubeSummation/Index.cshtml
<h3 class="box-title">Cube Summation</h3>

<div class="row" style="font-size:10px">
    Texto de ejemplo<br />

    2<br />
    4 5<br />
    UPDATE 2 2 2 4<br />
    QUERY 1 1 1 3 3 3<br />
    UPDATE 1 1 1 23<br />
    QUERY 2 2 2 4 4 4<br />
    QUERY 1 1 1 3 3 3<br />
    2 4<br />
    UPDATE 2 2 2 1<br />
    QUERY 1 1 1 1 1 1<br />
    QUERY 1 1 1 2 2 2<br />
    QUERY 2 2 2 2 2 2<br />
</div>

<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <label class="control-label">Texto Entrada</label>
        </div>
        <div class="form-group">
            <textarea id="TextoEntrada" rows="15"></textarea>
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label class="control-label">Texto Salida</label>
        </div>
        <div class="form-group">
            <textarea id="TextoSalida" rows="15" readonly="readonly"></textarea>
        </div>
    </div>
</div>

<button onclick="myFunction()" class="btn btn-success btn-sm">Proceso</button>


<script>
    function myFunction() {
        var url = '@Url.Content("~/")' + "CubeSummation/Proceso";
        $.getJSON(url, { texto: $("#TextoEntrada").val() }, function (data) {
            $('#TextoSalida').html(data);
        });
    }
</script>

CubeSummation.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CubeSummation.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CubeSummation.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="https://code.jquery.com/jquery-2.2.2.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CubeSummation.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CubeSummation" asp-action="Index">Cube Summation</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - CubeSummation.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>